name: Build and push dev containers

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-dev-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images for koyeb/tt-tailscale-ssh Ubuntu 22.04
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./tt-tailscale-ssh
          file: ./tt-tailscale-ssh/Dockerfile
          tags: |
            koyeb/tt-tailscale-ssh:ubuntu-22.04
            koyeb/tt-tailscale-ssh:latest

      - name: Build and push images for koyeb/tt-vsc-tunnel Ubuntu 22.04
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./tt-vsc-tunnel/Dockerfile
          tags: |
            koyeb/tt-vsc-tunnel:ubuntu-22.04
            koyeb/tt-vsc-tunnel:latest

      - name: Build and push images for koyeb/tt-ssh Ubuntu 22.04
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./tt-ssh
          file: ./tt-ssh/Dockerfile
          tags: |
            koyeb/tt-ssh:ubuntu-22.04
            koyeb/tt-ssh:latest
