name: Push Docker Images

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images for koyeb/tt-tailscale-ssh
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./tt-tailscale-ssh
          file: ./tt-tailscale-ssh/Dockerfile

      - name: Build and push images for koyeb/tt-vsc-tunnel
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./tt-vsc-tunnel/Dockerfile
